### ISSUE TITLE
Dropdown Arrow Styling Issue

### ISSUE THREAD

**Issue by matwright** [AkashDivya/SlimyCard-Animated-Flutter-Package#4]
Given that the BoxDecoration for the open button is explicitly set to Colors.white, this means the arrow cannot be seen when using
flutter's Material dark mode as the icon also appears white. Therefore explicitly setting the icon to black ensures it can always be seen regardless of theme settings.

I've sent a pull request to fix this.

**Comment by AkashDivya** [comment]
Thankyou for bringing this to my attention. Soon this will be fixed

**Comment by AkashDivya** [comment]
issue is fixed.
